#!/usr/bin/env node
// Copies the PDF renderer from ./innnvoice and the starter template from
// ./innnvoice.json into ./innnvoice.html, so the page stays one self-contained file.
//
//   node scripts/build-html.js           → rewrite innnvoice.html
//   node scripts/build-html.js --check   → exit 1 if innnvoice.html is out of date

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const cli = read('innnvoice');
const start = cli.indexOf('function renderInvoice(');
const end = cli.indexOf('\n// </core>');
if (start < 0 || end < 0) throw new Error('Could not find the <core> block in innnvoice.');
const core = cli.slice(start, end).trim();

const sample = JSON.stringify(JSON.parse(read('innnvoice.json')), null, '\t').replace(/<\//g, '<\\/');

const html = read('innnvoice.html');
const block = (name, note, body) => `// <${name}> ${note}\n${body}\n// </${name}>`;
const next = html
	.replace(/\/\/ <core>[\s\S]*?\/\/ <\/core>/, () => block('core', 'Generated by scripts/build-html.js from ./innnvoice; edit it there.', core))
	.replace(/\/\/ <sample>[\s\S]*?\/\/ <\/sample>/, () =>
		block('sample', 'Generated by scripts/build-html.js from ./innnvoice.json.', `const SAMPLE = ${sample};`),
	);

if (process.argv.includes('--check')) {
	if (next !== html) {
		console.error('✗ innnvoice.html is out of date. Run: node scripts/build-html.js');
		process.exit(1);
	}
	console.log('✓ innnvoice.html is up to date');
} else {
	fs.writeFileSync(path.join(root, 'innnvoice.html'), next);
	console.log('✓ Built innnvoice.html');
}
